-- ==========================================
-- EKSİK TABLOLAR: ÜRETİM GİRİŞ VE PARÇALAR
-- ==========================================

-- 1. uretim_girisleri tablosu
CREATE TABLE public.uretim_girisleri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id BIGINT REFERENCES public.models(id) ON DELETE CASCADE,
    getiren_personel_id BIGINT REFERENCES public.personnel(id) ON DELETE SET NULL,
    acilis_tarihi TIMESTAMPTZ,
    acan_personel_id BIGINT REFERENCES public.personnel(id) ON DELETE SET NULL,
    beden_eksik BOOLEAN DEFAULT false,
    beden_eksik_detay TEXT,
    aksesuar_eksik BOOLEAN DEFAULT false,
    aksesuar_eksik_detay TEXT,
    kumas_eksik BOOLEAN DEFAULT false,
    kumas_eksik_detay TEXT,
    numune_ayrildi BOOLEAN DEFAULT false,
    parca_sayisi INTEGER DEFAULT 0,
    notlar TEXT,
    durum TEXT DEFAULT 'beklemede',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. uretim_giris_parcalar tablosu
CREATE TABLE public.uretim_giris_parcalar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    giris_id BIGINT REFERENCES public.uretim_girisleri(id) ON DELETE CASCADE,
    parca_adi TEXT,
    fotograf_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS (Row Level Security) Aktifleştirme
ALTER TABLE public.uretim_girisleri ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.uretim_giris_parcalar ENABLE ROW LEVEL SECURITY;

-- Politikalar (Herkes okuyup yazabilir - geçici olarak veya projenin mevcut RLS yapısına uygun)
CREATE POLICY "Enable all for authenticated users on uretim_girisleri" ON public.uretim_girisleri FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated users on uretim_giris_parcalar" ON public.uretim_giris_parcalar FOR ALL USING (auth.role() = 'authenticated');

-- ==========================================
-- EĞER ANONİM ERİŞİM AÇIKSA (Mevcut yapıya göre):
-- ==========================================
CREATE POLICY "Enable all access for all users on uretim_girisleri" ON public.uretim_girisleri FOR ALL USING (true);
CREATE POLICY "Enable all access for all users on uretim_giris_parcalar" ON public.uretim_giris_parcalar FOR ALL USING (true);
