-- ==========================================
-- 09: YZ VEKTÖREL HAFIZA (RAG) TABLOLARI
-- ==========================================
-- İşletmenin "Agent" zekası için uzun süreli hafızası.
-- NOT: Supabase'de 'vector' eklentisi aktif olmalıdır.

-- 1. pgvector eklentisini aktifleştirin (Supabase'de genellikle açıktır ama garanti olsun)
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Modeller ve Kumaşlar için Hafıza Tablosu (Geçmiş Üretim Kayıtları)
CREATE TABLE IF NOT EXISTS public.model_memory_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id BIGINT REFERENCES public.models(id) ON DELETE SET NULL, -- Geçmiş bir modeli referans alabilir
    kumas_cinsi TEXT NOT NULL, -- "Pamuklu Şardonlu Üç İplik", "Süprem" vb.
    fire_orani DECIMAL(5,2),   -- Örn: 14.50 (Gerçekleşen fire oranı)
    karlilik_orani DECIMAL(5,2), -- Gerçekleşen fason kârlılık
    baglam_metni TEXT NOT NULL,  -- Yapay Zekanın okuyacağı düz metin ("2025'te bu kumaşta %14 fire verdik, kesim makineleri zorlandı...")
    embedding vector(1536), -- OpenAI (text-embedding-3-small) veya seçilecek LLM'in embedding boyutu
    eklenme_tarihi TIMESTAMPTZ DEFAULT NOW(),
    kategori TEXT DEFAULT 'uretim_tecrubesi' -- 'uretim_tecrubesi', 'kumas_tedarik', 'tasarim_risk' vb.
);

-- RLS (Row Level Security) Aktifleştirme
ALTER TABLE public.model_memory_embeddings ENABLE ROW LEVEL SECURITY;

-- Politikalar (Şimdilik herkes okuyup yazabilir)
CREATE POLICY "Enable all for authenticated users on memory" ON public.model_memory_embeddings FOR ALL USING (true);

-- 3. Performans için Vektör İndeksi (Hızlı arama)
CREATE INDEX ON public.model_memory_embeddings USING hnsw (embedding vector_cosine_ops);
