-- ==========================================
-- 10: AR-GE, TASARIM VE KOMUTA MERKEZİ TABLOLARI
-- ==========================================

-- 1. arge_projeleri (Trend, Model Fikri ve Karargah Onayı)
CREATE TABLE IF NOT EXISTS public.arge_projeleri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proje_kodu TEXT NOT NULL UNIQUE,
    proje_adi TEXT NOT NULL,
    hedef_kitle TEXT, -- 'Avrupa', 'Ortadoğu', 'İç Piyasa' vb.
    tahmini_kumas TEXT,
    hedef_maliyet DECIMAL(10,2),
    hedef_satis DECIMAL(10,2),
    trend_skoru INTEGER DEFAULT 0, -- Yapay Zeka Siber İstihbarat Skoru (1-10)
    trend_ozeti TEXT, -- YZ Tarafından Özetlenen Rapor
    durum TEXT DEFAULT 'taslak', -- 'taslak', 'numune_dikiminde', 'onay_bekliyor', 'onaylandi', 'reddedildi'
    yonetici_notu TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. zombi_numuneler (İlk Numune Dikimi ve Test Reçeteleri)
CREATE TABLE IF NOT EXISTS public.zombi_numuneler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arge_proje_id BIGINT REFERENCES public.arge_projeleri(id) ON DELETE CASCADE,
    kalip_suresi_dakika INTEGER DEFAULT 0,
    dikim_suresi_dakika INTEGER DEFAULT 0,
    harcanan_kumas_metre DECIMAL(5,2),
    kalipci_personel_id BIGINT REFERENCES public.personnel(id) ON DELETE SET NULL,
    numuneci_personel_id BIGINT REFERENCES public.personnel(id) ON DELETE SET NULL,
    zorluk_derecesi INTEGER DEFAULT 1, -- (1-10) İK Ajanı Adalet Terazisinde bunu primalacak
    notlar TEXT,
    medya_url TEXT, -- Sunum videoları/fotoğrafları için cloud linki
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. faz_takip (Saniye/Dakika Bazlı Efor ve Kronometrik Performans Takibi)
CREATE TABLE IF NOT EXISTS public.faz_takip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arge_proje_id BIGINT REFERENCES public.arge_projeleri(id) ON DELETE CASCADE,
    islem_turu TEXT NOT NULL, -- 'kalip_cizimi', 'kumas_kesimi', 'zombi_dikimi', 'medya_cekimi' vs
    baslangic_zaman TIMESTAMPTZ NOT NULL,
    bitis_zaman TIMESTAMPTZ,
    personel_id BIGINT REFERENCES public.personnel(id) ON DELETE SET NULL,
    durum TEXT DEFAULT 'devam_ediyor', -- 'devam_ediyor', 'tamamlandi'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS (Row Level Security) Aktifleştirme
ALTER TABLE public.arge_projeleri ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zombi_numuneler ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faz_takip ENABLE ROW LEVEL SECURITY;

-- Politikalar (Herkes okuyup yazabilir - Uygulama Güvenlik Kalkanı (App Logic) Yönetir)
CREATE POLICY "Enable all for authenticated users on arge_projeleri" ON public.arge_projeleri FOR ALL USING (true);
CREATE POLICY "Enable all for authenticated users on zombi_numuneler" ON public.zombi_numuneler FOR ALL USING (true);
CREATE POLICY "Enable all for authenticated users on faz_takip" ON public.faz_takip FOR ALL USING (true);
